### ISSUE TITLE
preprocessed data & pre-trained weights

### ISSUE THREAD

**Issue by dongqi-me** [nttcslab-nlp/RSTParser_EACL24#1]
Hello, thank you for your nice work. I was wondering if you plan to release the preprocessed data and pre-trained weights? This would facilitate our use in other tasks.

**Comment by arumaekawa** [comment]
Thank you for your interest in our work. We plan to relase the pre-trained QLoRA weights (as soon as possible), but we cannot release the preprocessed data.

**Comment by arumaekawa** [comment]
We open our pretrained weights at https://huggingface.co/collections/arumaekawa/rst-parser-with-llama-2-660cf1bf5dcbe4ca96541a42
