### ISSUE TITLE
Batch_size 16 with only one 3090 during training?

### ISSUE THREAD

**Issue by YuanWind** [nttcslab-nlp/RSTParser_EACL24#2]
When I experiment, one 3090 can set only 2 batch_size (even with quantization 4bit) . Something wrong with me?

**Comment by YuanWind** [comment]
llama-7B

**Comment by YuanWind** [comment]
oh, I see, --gradient_accumulation_steps 16 ?

**Comment by arumaekawa** [comment]
Yes, you're right, We set `--per_device_train_batch_size 1` and `--gradient_accumulation_steps 16` (as default).
